import React from 'react';
declare type typeProps = 'basic' | 'line';
declare type sizeProps = 'big' | 'medium' | 'small';
declare type TextareaPropsType = {
    type: typeProps;
    size?: sizeProps;
    onChange: (value: string) => void;
    className?: string;
    value: string;
    tabIndex?: number;
    readOnly?: boolean;
    placeholder?: string;
    onFocus?: () => void;
    onKeyDown?: (e: React.KeyboardEvent<HTMLTextAreaElement>) => void;
    onKeyUp?: (e: React.KeyboardEvent<HTMLTextAreaElement>) => void;
    onBlur?: () => void;
    rows?: number;
    cols?: number;
    borderColor: string;
};
declare function Textarea({ type, size, onChange, className, value, tabIndex, readOnly, placeholder, onFocus, onKeyDown, onKeyUp, onBlur, rows, cols, borderColor, }: TextareaPropsType): JSX.Element;
export default Textarea;
